services:
  mariadb:
    image: Users
    container_name: Users
    build:
      context: Users/app
    env_file: ".env"
    networks:
      - ft_transcendence
    restart: on-failure

  server:
    container_name: server
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/node
      - /node/node_modules
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./src
          target: /node/src
        - action: rebuild
          path: package.json