services:
  users:
    image: users
    container_name: users
    build:
      context: api/users/
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ft_transcendence
    env_file:
      - .env
    volumes:
      - users-data:/app/database
      - ./uploads:/app/uploads
    restart: unless-stopped

  game:
    image: game
    container_name: game
    build:
      context: api/game
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8082/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ft_transcendence
    volumes:
      - game-data:/app/database
    restart: on-failure

  matchmaking:
    image: matchmaking
    container_name: matchmaking
    build:
      context: api/matchmaking
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8083/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ft_transcendence
    volumes:
      - matchmaking-data:/app/database
    restart: on-failure

  auth:
    image: auth
    container_name: auth
    build:
      context: api/auth
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8084/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ft_transcendence
    volumes:
      - auth-data:/app/database
    restart: on-failure

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: api/nginx
    volumes:
      - ./uploads:/usr/share/nginx/front/uploads
    ports:
      - "8443:443"
    depends_on:
      users:
        condition: service_healthy
      tournament:
        condition: service_healthy
      matchmaking:
        condition: service_healthy
      game:
        condition: service_healthy
      authentication:
        condition: service_healthy
    networks:
      - ft_transcendence
    restart: on-failure

networks:
  ft_transcendence:
    driver: bridge

volumes:
  users-data:
    driver: local
  authentication-data:
    driver: local
  matchmaking-data:
    driver: local
  game-data:
    driver: local
  tournament-data:
    driver: local


