services:
  Users:
    image: Users
    container_name: Users
    build:
      context: Users
    env_file:
      - ".env"
    networks:
      - ft_transcendence
    restart: on-failure

  Tournament:
    image: Tournament
    container_name: Tournament
    build:
      context: Tournament
    env_file:
      - ".env"
    networks:
      - ft_transcendence
    restart: on-failure

  Game:
    image: Game
    container_name: Game
    build:
      context: Game
    env_file:
      - ".env"
    networks:
      - ft_transcendence
    restart: on-failure

  Matchmaking:
    image: Matchmaking
    container_name: Matchmaking
    build:
      context: Matchmaking
    env_file:
      - ".env"
    networks:
      - ft_transcendence
    restart: on-failure

  Authentification:
    image: Authentification
    container_name: Authentification
    build:
      context: Authentification
    env_file:
      - ".env"
    networks:
      - ft_transcendence
    restart: on-failure

  Nginx:
    image: Nginx
    container_name: Nginx
    build:
      context: Nginx
    env_file:
      - ".env"
    ports:
      - "8080:8080"
    depends_on:
      - Users
      - Matchmaking
      - Authentification
      - Game
      - Tournament
    networks:
      - ft_transcendence
    restart: on-failure

networks:
  ft_transcendence:
      driver: bridge

volumes:
  Nginx-data:
    driver: local
  Authentification-data:
    driver: local
  Matchmaking-data:
    driver: local
  Game-data:
    driver: local
  Tournament-data:
    driver: local
  Users-data:
    driver: local

